name: Build

on:
  push:
  pull_request:
    types:
      - opened
      - reopened

env:
  USERNAME: ${{ secrets.GITHUB_TOKEN }}
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      - name: Build and Publish to GitHub Packages
        run: ./gradlew build
      - name: Upload the files
        uses: actions/upload-artifact@v4
        with:
          name: physics-minecraft
          path: build/libs/*.jar
